ALTER TABLE users
    MODIFY COLUMN role ENUM('ADMIN', 'FACULTY', 'RESIDENT', 'STUDENT', 'VENDOR');

UPDATE users
SET role = 'ADMIN'
WHERE role = 'FACULTY';

ALTER TABLE users
    MODIFY COLUMN role ENUM('ADMIN', 'RESIDENT', 'STUDENT', 'VENDOR');
