export const CAMPUSES = [
  'CPUT - Bellville',
  'CPUT - District Six',
  'CPUT - Granger Bay',
  'CPUT - Mowbray',
  'CPUT - Wellington',
  'CPUT - George',
  'University of Cape Town',
  'University of the Western Cape',
  'Stellenbosch University',
  'University of Johannesburg',
  'University of Pretoria',
  'University of the Witwatersrand',
  'University of KwaZulu-Natal',
  'University of the Free State',
  'Nelson Mandela University',
  'Rhodes University',
  'University of Limpopo',
];
